/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/lburgazzoli/k8s-controller-playground/api/playground/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// AgentLister helps list Agents.
// All objects returned here must be treated as read-only.
type AgentLister interface {
	// List lists all Agents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Agent, err error)
	// Agents returns an object that can list and get Agents.
	Agents(namespace string) AgentNamespaceLister
	AgentListerExpansion
}

// agentLister implements the AgentLister interface.
type agentLister struct {
	listers.ResourceIndexer[*v1alpha1.Agent]
}

// NewAgentLister returns a new AgentLister.
func NewAgentLister(indexer cache.Indexer) AgentLister {
	return &agentLister{listers.New[*v1alpha1.Agent](indexer, v1alpha1.Resource("agent"))}
}

// Agents returns an object that can list and get Agents.
func (s *agentLister) Agents(namespace string) AgentNamespaceLister {
	return agentNamespaceLister{listers.NewNamespaced[*v1alpha1.Agent](s.ResourceIndexer, namespace)}
}

// AgentNamespaceLister helps list and get Agents.
// All objects returned here must be treated as read-only.
type AgentNamespaceLister interface {
	// List lists all Agents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Agent, err error)
	// Get retrieves the Agent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Agent, error)
	AgentNamespaceListerExpansion
}

// agentNamespaceLister implements the AgentNamespaceLister
// interface.
type agentNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.Agent]
}
