# permissions for end users to edit agents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller-playground
    app.kubernetes.io/managed-by: kustomize
  name: playgriund-agent-editor-role
rules:
- apiGroups:
  - playgriund.lburgazzoli.github.io
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - playgriund.lburgazzoli.github.io
  resources:
  - agents/status
  verbs:
  - get
