---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dapr-control-plane-role
rules:
- apiGroups:
  - playground.lburgazzoli.github.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - playground.lburgazzoli.github.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - playground.lburgazzoli.github.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
