/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/lburgazzoli/k8s-controller-playground/api/playground/v1alpha1"
	playgroundv1alpha1 "github.com/lburgazzoli/k8s-controller-playground/pkg/client/applyconfiguration/playground/v1alpha1"
	scheme "github.com/lburgazzoli/k8s-controller-playground/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentsGetter has a method to return a AgentInterface.
// A group's client should implement this interface.
type AgentsGetter interface {
	Agents(namespace string) AgentInterface
}

// AgentInterface has methods to work with Agent resources.
type AgentInterface interface {
	Create(ctx context.Context, agent *v1alpha1.Agent, opts v1.CreateOptions) (*v1alpha1.Agent, error)
	Update(ctx context.Context, agent *v1alpha1.Agent, opts v1.UpdateOptions) (*v1alpha1.Agent, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agent *v1alpha1.Agent, opts v1.UpdateOptions) (*v1alpha1.Agent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Agent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AgentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Agent, err error)
	Apply(ctx context.Context, agent *playgroundv1alpha1.AgentApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Agent, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, agent *playgroundv1alpha1.AgentApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Agent, err error)
	AgentExpansion
}

// agents implements AgentInterface
type agents struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Agent, *v1alpha1.AgentList, *playgroundv1alpha1.AgentApplyConfiguration]
}

// newAgents returns a Agents
func newAgents(c *PlaygroundV1alpha1Client, namespace string) *agents {
	return &agents{
		gentype.NewClientWithListAndApply[*v1alpha1.Agent, *v1alpha1.AgentList, *playgroundv1alpha1.AgentApplyConfiguration](
			"agents",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Agent { return &v1alpha1.Agent{} },
			func() *v1alpha1.AgentList { return &v1alpha1.AgentList{} }),
	}
}
