apiVersion: playground.lburgazzoli.github.io/v1alpha1
kind: Component
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller-playground
    app.kubernetes.io/managed-by: kustomize
  name: component-sample
spec:
  # TODO(user): Add fields here
